# -*- coding: utf-8 -*-
"""SQL_R_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145oLzOSKfpz6a65Ot2SXV2avMKfBL9JA
"""

install.packages("sqldf")

library(sqldf)

library(readr)

customers<-read_csv("customers.csv")

head(customers)

colnames(customers)

complaints<-read_csv("complaints.csv")

head(complaints)

colnames(complaints)

deliveries<-read_csv("deliveries.csv")

head(deliveries)

colnames(deliveries)

complaints<-read_csv("complaints.csv")

head(complaints)

colnames(complaints)

colSums(is.na(customers))

colSums(is.na(deliveries))

library(dplyr)

complaints<-distinct(complaints)

deliveries<-distinct(deliveries)

str(deliveries)

library(readr)

complaints<-read_csv("complaints.csv")

deliveries<-read_csv("deliveries.csv")

str(deliveries)

install.packages("sqldf" , repos="http://cloud.r-project.org")

library(sqldf)

complaint_delivery_analysis <- sqldf("

SELECT
    c.order_id,
    c.severity,
    d.delivery_status,
    d.route_distance_km,
    d.customer_rating_post_delivery

FROM complaints c

JOIN deliveries d
ON c.order_id = d.order_id

")

head(complaint_delivery_analysis)

drivers <- read_csv("drivers.csv")

head(drivers)

driver_delivery_analysis <- sqldf("

SELECT
    dr.driver_id,
    d.delivery_status,
    d.route_distance_km,
    d.customer_rating_post_delivery

FROM drivers dr

JOIN deliveries d
ON dr.driver_id = d.driver_id

")

head(driver_delivery_analysis)

incidents <- read_csv("incidents.csv")

head(incidents)

library(sqldf)
library(readr)

incidents <- read_csv("incidents.csv")

complaints <- read_csv("complaints.csv")

complaints <- read_csv("complaints.csv")

incidents <- read_csv("incidents.csv")

incident_complaint_analysis <- sqldf("

SELECT
    i.incident_id,
    i.severity,
    c.complaint_type,
    c.status,
    c.resolution_days

FROM incidents i

JOIN deliveries d
ON i.delivery_id = d.delivery_id

JOIN complaints c
ON d.order_id = c.order_id

LIMIT 10

")

head(incident_complaint_analysis)

print(incident_complaint_analysis)

library(ggplot2)

ggplot(deliveries, aes(x = delivery_status)) +
  geom_bar(fill = "steelblue") +
  labs(
    title = "Distribution of Delivery Status",
    x = "Delivery Status",
    y = "Count"
  )

ggplot(complaints, aes(x = complaint_type)) +
  geom_bar(fill = "darkred") +
  labs(
    title = "Distribution of Complaint Types",
    x = "Complaint Type",
    y = "Count"
  )

import pandasas pd
import matplotlib.pyplot as plt

import pandas as pd
import matplotlib.pyplot as plt

import pandas as pd

deliveries = pd.read_csv("deliveries.csv")

deliveries.head()

deliveries["delivery_status"].value_counts()

deliveries["delivery_status"].value_counts().plot(kind="bar")

plt.title("Delivery Status Distribution")

plt.xlabel("Delivery Status")

plt.ylabel("Count")

plt.show()

import seaborn as sns

sns.countplot(x="delivery_status", data=deliveries)

plt.title("Delivery Status Distribution")

plt.show()

import pandas as pd

complaints = pd.read_csv("complaints.csv")

complaints["complaint_type"].value_counts()

complaints["complaint_type"].value_counts().plot(kind="bar")

plt.title("Complaint Type Distribution")

plt.xlabel("Complaint Type")

plt.ylabel("Count")

plt.show()

import numpy as np

np.mean(deliveries["route_distance_km"])

install.packages("sqldf" , repos="https://cloud.r-project.org")

library(sqldf)

library(readr)

deliveries <- read_csv("deliveries.csv")

deliveries <- as.data.frame(deliveries)

optimized_query <- sqldf(
"SELECT
delivery_status,
COUNT(*) AS total_deliveries
FROM deliveries
GROUP BY delivery_status
")

head(optimized_query)

print(optimized_query)